Made it look fancy
queer/GFYPL pull request #9
Opened 2021-04-12 21:38 UTC by SUPERN00Bthefirst

If you don't like my changes Frick you

2021-04-12 22:28 UTC, queer requested changes
Thank you for your contribution!

There were a bunch of small spelling mistakes that needed to be corrected, hence all the suggestions. However, I'm not particularly inclined to merge this unless the GFYCLA gets a similar rework.

2021-04-12 22:28 UTC, queer commented on GFYPL
> +            1. You are no permitted to use any of the licenced material
```suggestion
            1. You are not permitted to use any of the licenced material
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +                        to give a responce sattisfying the terms in
```suggestion
                        to give a response satisfying the terms in
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +                        to give a responce sattisfying the terms in
```suggestion
                        to give a response satisfying the terms in
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +                        to give a responce sattisfying the terms in
```suggestion
                        to give a response satisfying the terms in
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +            3. You are not permitted to create coppies (Private or Public)
```suggestion
            3. You are not permitted to create copies (Private or Public)
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +                        to give a responce sattisfying the terms in
```suggestion
                        to give a response satisfying the terms in
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +                        sattisfying the terms in 1(a).
```suggestion
                        means you are obligated to give a response 
                        satisfying the terms in 1(a).
```

2021-04-12 22:28 UTC, queer commented on GFYPL
> +                        to give a responce sattisfying the terms
```suggestion
                        to give a response satisfying the terms
```

2021-04-12 23:18 UTC, SUPERN00Bthefirst commented
In conclusion, GitHub needs spellcheck

2021-04-12 23:19 UTC, SUPERN00Bthefirst commented
I shall begin work on upgrading the Other one then!

2021-04-13 15:45 UTC, SUPERN00Bthefirst commented
The GFYCLA seems to have been fixed by [#10](https://github.com/queer/GFYPL/pull/10) As such I will unmark this as a draft.

2021-04-14 10:49 UTC, queer approved these changes
Just needs the conflicts fixed \^\^

2021-04-14 11:36 UTC, valoeghese approved these changes

2021-04-14 14:47 UTC, SUPERN00Bthefirst commented
All ready!

2021-04-14 14:57 UTC, queer commented
Thank you for your contribution ^^

2021-04-14 14:57 UTC, merged